### ISSUE TITLE
New syntax is slightly 'off'?

### ISSUE THREAD

**Issue by inlikealion** [inuitcss/tools.widths#5]
Hey @csswizardry, I dig the clarity you are bringing with the new class names, and am sure once I dig into the the new suffixes it will click and I'll appreciate the added utility.

In the meantime, I take slight issue with the `x-of-y` syntax over the previous `ex-why` syntax. The module is for example, "one half" of any given layout space. There are NOT necessarily a total of two items in a given space, thus "one-of-two" is not accurate and even implies an incorrect mental model of the number of items or their layouts. I think it lacks clarity for the uninitiated.

I'd vote for reverting the non fractional syntax to u-one-half from u-one-of-two.

**Comment by Crawleyprint** [comment]
@inlikealion why not try fractions? There are initiatives to leave fractions as the only syntax: https://github.com/inuitcss/trumps.widths/issues/11 (at least @nenadjelovac suggested that)

**Comment by nenadjelovac** [comment]
Hey @inlikealion,

I agree with you that this naming is different mental model. That's one more reason why I'd suggest it goes :)

As @Crawleyprint said, I am suggesting inuit leaves only fractions (a bit more opinionated but forces consistent usage). Now you get `.u-1-of-4` (check [here](https://github.com/inuitcss/tools.widths/blob/master/_tools.widths.scss#L15)) and `.u-1/4` seems a lot better.

Also, I find using numbers instead of words (as in previous version) is easier to use in markup, easier to maintain (eg. changing `1/6` to `2/6` vs `one-sixth` to `five-sixths`), and you get a clearer picture of what's going on (check comparison below).

``` html
  <div class="layout__item  u-one-half  u-one-third-md  u-one-sixth-lg-and-up">
    ...
  </div>
  <div class="layout__item  u-one-half  u-two-thirds-md  u-five-sixths-lg-and-up">
    ...
  </div>
```

``` html
  <div class="layout__item  u-1/2  u-1/3-md  u-1/6-lg-and-up">
    ...
  </div>
  <div class="layout__item  u-1/2  u-2/3-md  u-5/6-lg-and-up">
    ...
  </div>
```

Also, one can easily mess up things with a simple typo (and not even get it). Eg. `5/12` is less prone to error than `five-twelfths` (especially for us non-native english speakers).

Other than that, now that widths are dynamically generated it's hard to leave versions with words.

**Comment by csswizardry** [comment]
The reason I’ve moved away from `.one-half`, `.three-quarters` etc. is that while it makes sense for (British) English people, it makes a lot less sense for non-English speakers.

Americans say fourths rather than quarters (which is them doing English wrong, but still :P), and to anyone who isn’t fluent in English, I’m pretty sure classes like `.six-twelfths` are a total nightmare.

The reason I’d like to offer something other than `.1/4` is in case any templating languages etc. trip up over forward-slashes (`/`) in markup. It makes for a completely valid classname, but is still unconventional.

Thoughts on solving the internationalisation _and_ the alternative-to-a-/ problems?

**Comment by patrick-wc** [comment]
@csswizardry I would submit a bug report to said templating languages instead. Fractions are the way to go! ;)

**Comment by Crawleyprint** [comment]
@zerodburn +1 :D 
However, until that, I think @csswizardry is right when it comes to alternate syntax. This use case with templating engines didn't cross my mind before

**Comment by anselmh** [comment]
When you regex via JS over such fraction classes this might also fail. So while I think they’re pretty nice it should still be possible to opt out of that due to library or templating engine support.

**Comment by Crawleyprint** [comment]
@anselmh can you give an example where it fails at js regexing (after escaping, of course)? I was thinking that might be the case, but, so far, I got no errors.

**Comment by anselmh** [comment]
Yeah if you escape it it’s not interfering but there are enough scripts that don’t do that out there. ;) That’s my concern.

**Comment by nenadjelovac** [comment]
I didn't mention templating languages because I assumed it's for developers using them to fix this issue (or for developer of the templating language as @zerodburn suggested), not css framework. Similar to whitespaces. Eg. http://hastebin.com/yalidubedu.php (from [this tweet](https://twitter.com/inuitcss/status/524234753374191616)).

But on the other side, whitespaces are (at the moment) hard to fix on css side without consequences, so no alternative for this use case (unlike with `/` for fractions).

So I do realise my suggestion is maybe too much. Any ideas how to approach this?

> Thoughts on solving the internationalisation and the alternative-to-a-/ problems?

internationalisation is solved with numbers for sure ;)

**Comment by Crawleyprint** [comment]
@anselmh you're right about all kinds of scripts, even jQuery doesn't work out of the box, but needs to have slash escaped by two backslashes. However, and I'm only reasoning out loud here -- if you're in need to retrieve anything from javascript only by purely presentational class that can (and most likely will) change at some point in future, you're doing something wrong. So I wouldn't consider this js issues to be a show-stopper, rather an (unintentional) safe-guard which preserves mixing of concerns.

Anyway, here's quick status for js with fraction naming convention (there might be more) for those who're interested:
- jQuery works, but needs escaping with two backslashes `$('.1\\/2')`, otherwise returns empty set
- `document.getElementsByClassName` and `element.classList` and it's methods work without any escaping
- `document.querySelectorAll` doesn't work neither with or without escaping, throws an error

**Comment by patrick-wc** [comment]
Not having `document.querySelectorAll` support on first glance seems like quite a big gotcha. However, on second thoughts, you should really be using a js- prefix for all class names to do with js interaction anyway - so another developer who works on your project can immediately see that there is some sort of js dependency involved - so I don't think its such a big deal. In fact, you could argue that using fractions in width class names encourages js- prefixing of class names to do with behaviour. 

@csswizardry I'm working my way through your More Transparent UI Code article this weekend. Really thorough and an excellent read. Cheers.
